TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devkeithleyK2410.db
DB_INSTALLS += $(TOP)/keithleyK2410Sup/devkeithleyK2410.proto

#=======================================
include $(TOP)/configure/RULES
